# Generated by Django 3.2.5 on 2022-06-12 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutShop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_logo', models.ImageField(blank=True, upload_to='shop_images')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('shop_address', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('usertype', models.CharField(choices=[('S', 'shop'), ('C', 'customer')], max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.order')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('type', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, default=0, null=True)),
                ('available_no', models.IntegerField(blank=True, null=True)),
                ('available_status', models.BooleanField(default=True)),
                ('more_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('more_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('more_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('more_image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('more_image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.aboutshop')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.products')),
            ],
        ),
        migrations.AddField(
            model_name='aboutshop',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.customer'),
        ),
    ]
